org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official
kotlin.incremental=true

# BuildConfig
android.defaults.buildfeatures.buildconfig=true

# Compose
android.enableCompose=true
